# Generated by Django 5.2.7 on 2025-11-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('legal', 'Protección Legal'), ('medica', 'Atención Médica'), ('laboral', 'Derechos Laborales'), ('licencias', 'Licencias Maternales')], max_length=50)),
                ('icono', models.CharField(default='⚖️', max_length=10)),
                ('descripcion_corta', models.TextField(max_length=200)),
                ('descripcion_completa', models.TextField()),
                ('que_hacer', models.TextField(help_text='Qué hacer en esta situación')),
                ('donde_acudir', models.TextField(help_text='Dónde acudir por ayuda')),
                ('leyes_aplicables', models.TextField(blank=True, help_text='Leyes que respaldan este derecho')),
                ('ejemplos', models.TextField(blank=True, help_text='Ejemplos de casos reales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caso de Problema',
                'verbose_name_plural': 'Casos de Problemas',
                'ordering': ['categoria', 'titulo'],
            },
        ),
    ]
